rootfs: scripts name change

diff --git a/buildquantumvis/rootfs/8create-drive-img b/buildquantumvis/rootfs/8create-drive-img
--- a/buildquantumvis/rootfs/8create-drive-img
+++ b/buildquantumvis/rootfs/8create-drive-img
@@ -12,6 +12,12 @@ if ! which openssl >/dev/null ;then
  exit 1
 fi
 
+which mkfs.btrfs >/dev/null
+if [ $? -ne 0 ];then
+ echo 'ERROR utility mkfs.btrfs missing. aborting.'
+ exit 1
+fi
+
 . /etc/rc.d/PUPSTATE
 . ${E1}/rootfs/etc/DISTRO_SPECS
 
@@ -222,5 +228,6 @@ losetup -d ${LOOP3}
 mv -f ${SKELETON_NAME}.img qv-${DISTRO_VERSION}-${DISTRO_TARGETARCH}.img
 md5sum qv-${DISTRO_VERSION}-${DISTRO_TARGETARCH}.img > md5sum.txt
 sync
-echo "qv-${DISTRO_VERSION}-${DISTRO_TARGETARCH}.img has been created"
+echo "qv-${DISTRO_VERSION}-${DISTRO_TARGETARCH}.img has been created."
+echo "Here: ${E1}/export"
 ###end###
