removed @home subvolume

diff --git a/buildquantumvis/initrd/initrd-tree-skeleton/sbin/delete-snapshots b/buildquantumvis/initrd/initrd-tree-skeleton/sbin/delete-snapshots
--- a/buildquantumvis/initrd/initrd-tree-skeleton/sbin/delete-snapshots
+++ b/buildquantumvis/initrd/initrd-tree-skeleton/sbin/delete-snapshots
@@ -78,13 +78,14 @@ do
   exit 4
  fi
  btrfs subvolume sync /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@qv
- btrfs subvolume delete /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home
- if [ $? -ne 0 ];then
-  echo "${S130:-ERROR failed to delete:} /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home"
-  echo "${S131:-This is bad. Avoid using this snapshot until it can be repaired.}"
-  exit 4
- fi
- btrfs subvolume sync /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home
+ #20240928 removed @home...
+ #btrfs subvolume delete /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home
+ #if [ $? -ne 0 ];then
+ # echo "${S130:-ERROR failed to delete:} /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home"
+ # echo "${S131:-This is bad. Avoid using this snapshot until it can be repaired.}"
+ # exit 4
+ #fi
+ #btrfs subvolume sync /mnt/${WKG_DEV}/${WKG_DIR}${aS}/@home
  rm -rf /mnt/${WKG_DEV}/${WKG_DIR}${aS}
  sync
  echo -n "${aS} " >/sdeleted
diff --git a/buildquantumvis/initrd/initrd-tree-skeleton/sbin/take-snapshot b/buildquantumvis/initrd/initrd-tree-skeleton/sbin/take-snapshot
--- a/buildquantumvis/initrd/initrd-tree-skeleton/sbin/take-snapshot
+++ b/buildquantumvis/initrd/initrd-tree-skeleton/sbin/take-snapshot
@@ -7,7 +7,7 @@ PATHDEF="$3" #ex: quantumvis/1
 
 #we want to take snapshots of these:
 #/mnt/${WKG_DEV}/${WKG_DIR}@qv
-#/mnt/${WKG_DEV}/${PATHDEF}/@home
+#/mnt/${WKG_DEV}/${PATHDEF}/@home #20240928 no longer have @home
 #20240403 no longer have @data subvolume...
 ##/mnt/${WKG_DEV}/${PATHDEF}/@data
 
@@ -51,12 +51,14 @@ if [ $? -ne 0 ];then
  rm -rf /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}
  exit 2
 fi
-btrfs subvolume snapshot /mnt/${WKG_DEV}/${PATHDEF}/@home /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}/@home
-if [ $? -ne 0 ];then
- echo "${S110:-Failed to create snapshot:} /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}/@home"
- rm -rf /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}
- exit 3
-fi
+#20240928 no longer have @home...
+#btrfs subvolume snapshot /mnt/${WKG_DEV}/${PATHDEF}/@home /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}/@home
+#if [ $? -ne 0 ];then
+# echo "${S110:-Failed to create snapshot:} /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}/@home"
+# rm -rf /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}
+# exit 3
+#fi
+
 #20240403 @data no longer exists...
 #btrfs subvolume snapshot /mnt/${WKG_DEV}/${PATHDEF}/@data /mnt/${WKG_DEV}/${WKG_DIR}${SNAPNEW}/@data
 #if [ $? -ne 0 ];then
